### ISSUE TITLE
Re-investigate missing tree issue

### ISSUE THREAD

**Issue by msridhar** [kelloggm/object-construction-checker#106]
On the [av-missing-tree](https://github.com/kelloggm/object-construction-checker/tree/av-missing-tree) branch I have introduced a runtime check that exposes a case where a `Tree` is unexpectedly missing while a checker is running.  To reproduce, check out that branch and run:
```
./gradlew :returnsrcvr-checker:test --tests '*AutoValue*'
```
This produces the following exception:
```
  Exception: java.lang.RuntimeException: no tree for superclass Animal.Builder while processing setName(java.lang.String) in AutoValue_Animal.Builder; 
Stack trace: 
org.checkerframework.checker.returnsrcvr.ReturnsRcvrAnnotatedTypeFactory$ReturnsRcvrTypeAnnotator.isBuilderSetter(ReturnsRcvrAnnotatedTypeFactory.java:100)
  org.checkerframework.checker.returnsrcvr.ReturnsRcvrAnnotatedTypeFactory$ReturnsRcvrTypeAnnotator.visitExecutable(ReturnsRcvrAnnotatedTypeFactory.java:61)
  org.checkerframework.checker.returnsrcvr.ReturnsRcvrAnnotatedTypeFactory$ReturnsRcvrTypeAnnotator.visitExecutable(ReturnsRcvrAnnotatedTypeFactory.java:43)
  org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedExecutableType.accept(AnnotatedTypeMirror.java:1027)
  org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.scan(AnnotatedTypeScanner.java:103)
  org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.visit(AnnotatedTypeScanner.java:91)
  org.checkerframework.framework.type.typeannotator.ListTypeAnnotator.scan(ListTypeAnnotator.java:51)
  org.checkerframework.framework.type.typeannotator.ListTypeAnnotator.scan(ListTypeAnnotator.java:19)
  org.checkerframework.framework.type.visitor.AnnotatedTypeScanner.visit(AnnotatedTypeScanner.java:91)
  org.checkerframework.framework.type.GenericAnnotatedTypeFactory.addComputedTypeAnnotations(GenericAnnotatedTypeFactory.java:1488)
...
```
So, while running the type annotator on a method in the generated `AutoValue_Animal.Builder` class, the `Tree` for its superclass `Animal.Builder` is missing (i.e., calling `declarationFromElement()` on its `TypeElement` returns `null`).  This is in spite of the fact that `Animal.Builder` was clearly compiled from source during the same `javac` invocation.

@kelloggm perhaps this will help you dig deeper on these missing tree issues.

/cc @mernst @ranmanli

**Comment by mernst** [comment]
This is not urgent.  The checker is coded to use Elements which works around it.  But it would be nice to get to the bottom of this and/or document what a type-checker needs to do to avoid problems.

Manu speculates that the tree was available in the first round, but got garbage-collected by the time that newly-generated code is processed in the second round (so the newly-generated code's superclass's tree is not available).

**Comment by msridhar** [comment]
> Manu speculates that the tree was available in the first round, but got garbage-collected by the time that newly-generated code is processed in the second round (so the newly-generated code's superclass's tree is not available).

@smillst @wmdietl FYI.  Have you seen cases where a tree is available in one annotation-processing round but not in a subsequent round?  This is for a case where Checker Framework is running alongside an annotation processor that generates code, like AutoValue.  There may some non-obvious behavior here that should be documented in the Checker Framework manual.

**Comment by smillst** [comment]
I haven't seen such a case, but I've never used the Checker Framework with another annotation processor.  One thing to keep in mind, `declarationFromElement()` is just a wrapper around `com.sun.source.util.Trees#getTree(javax.lang.model.element.Element)`.

**Comment by msridhar** [comment]
Thanks @smillst.  This may be a rather narrow case, now that I think about it more.  In general, it is never really safe to assume that a `Tree` exists for any type other than the one whose AST the checker is currently traversing, since the other type might be defined in bytecode.  Here, it seemed like it would be a safe assumption since we know the other type must have been defined in a source file, but with multiple annotation processing rounds even that is not sufficient to guarantee a tree's presence.

I am not sure this rises to the level of needing to be documented in the manual; but it is an interesting corner case.

**Comment by mernst** [comment]
@msridhar Based on your last comment, should we close this issue?

**Comment by msridhar** [comment]
Yes I will close it.  We don't need to spend time investigating further.
