### ISSUE TITLE
Error message formatting does not work with Checker Framework master branch

### ISSUE THREAD

**Issue by msridhar** [kelloggm/object-construction-checker#140]
Our logic for adding nicer error message formatting with the `finalizer.invocation.invalid` error type no longer works when using the master branch of the Checker Framework.  We should keep this in mind when updating to the next Checker Framework release.

Unfortunately I don't think we have a regression test checking for the error message formatting.  @kelloggm is there any way to add such a test?

/cc @mernst

**Comment by kelloggm** [comment]
Mike and I figured out a nice way to avoid this by adding a new protected method to `BaseTypeVisitor`, so I'll be able to fix this once that lands (I'll probably also just wait for the next CF release, unless you object)

**Comment by msridhar** [comment]
Sure we can definitely wait until the next release.  I just opened the issue so we wouldn't forget about this when we upgrade.

**Comment by msridhar** [comment]
Now that #160 has landed, we have bumped to CF 3.4.0, so we can fix this properly
